name: 'Bug Report:'
description: Found a Bug? Report it Here!
assignees: [1337Syntax]
body:
  - type: input
    attributes:
      label: 'DiscordChatExporterPy Version:'
      description: What Version of the Library are You Using?
      placeholder: '2.9.0'
    validations:
      required: true
  - type: input
    attributes:
      label: 'Discord.PY Version:'
      description: What Version of `discord.py` (or Fork) are You Using?
      placeholder: '2.4.0'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Bug Description:'
      description: Describe What the Bug is & How it Happened.
      placeholder: 'Code-Blocks are Not being Rendered Correctly in the Output . . .'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Bug Traceback:'
      description: If You Have a Traceback, Please Paste it Here.
      placeholder: '```python\nTraceback (most recent call last):\n. . .```'
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: 'Checklist:'
      description: 'Please Check the Following:'
      options:
        - label: 'I Have Searched the Issues to Ensure this Bug has Not Already Been Reported/Resolved.'
          required: true
        - label: 'I Have Confirmed this Bug is Reproducible.'
          required: true
        - label: 'I Have Filled Out All the Required Fields Above.'
          required: true
  - type: textarea
    attributes:
      label: 'Additional Information:'
      description: Any Additional Information to Know.
    validations:
      required: false
