blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/1337Syntax/DiscordChatExporterPy/discussions
    about: Need Help with Using the Library? Create a Discussion!
