name: 'Feature Request:'
description: Want to Request a New Feature? Submit it Here!
assignees: [1337Syntax]
body:
  - type: textarea
    attributes:
      label: 'Feature Description:'
      description: Describe the Feature You Would Like to See Added.
      placeholder: 'I Would Like to See a New Command Added to Export . . .'
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Feature Justification:'
      description: Why Should this Feature be Added?
      placeholder: 'This Feature Would Make it Easier to . . .'
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 'Checklist:'
      description: 'Please Check the Following:'
      options:
        - label: 'I Have Searched the Issues to Ensure this Feature has Not Already Been Requested.'
          required: true
        - label: 'I Have Confirmed this Feature is Necessary.'
          required: true
        - label: 'I Have Filled Out All the Required Fields Above.'
          required: true
  - type: textarea
    attributes:
      label: 'Additional Information:'
      description: Any Additional Information to Know.
    validations:
      required: false
